---
title: "Vignette on the knapsack package"
author: "Yumeng Li, Mattias Karlsson, Ashraf Sarhan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Vignette Goal
The package contain three different functions for solving what is called the knapsack problem.
The knapsack problem is a discrete optimization problem where we have a knapsack that can take a
limited weight W and we want to fill this knapsack with a number of items i = 1, ...,n, each with a
weight wi and a value vi. 
The goal is to find the knapsack with the largest value of the elements added
to the knapsack. 
To solve this problem is NP which means that (most researchers belive) there are no
polynomial time algorithm to solve this problem.

## Function Discription

This package contains four different functions for solving the knapsack problem.

Brute Force function: brute_force_knapsack()

Dynamic approch: knapsack_dynamic()

Greedy approch: greedy_knapsack()

```
# system.time(brute_force_knapsack(knapsack_objects[1:16,], 2000))

# Yumeng's pc
# system.time(brute_force_knapsack(knapsack_objects[1:16,], 2000))
# user  system elapsed 
# 57.44  0.00 57.47 


# system.time(knapsack_dynamic(knapsack_objects[1:16,], 2000))
# user  system elapsed
# 6.30 0.00 6.32

#system.time(greedy_knapsack(knapsack_objects, 2000))

# n = 1 000 000 ; size = 2000 ; Mattias computer
# user  system elapsed 
# 0.41    0.00    0.41 

```


## Unit Tests

The unit tests checks wheter the dataset is in correct format for the package funtions

```
context('Test Brute force search')

set.seed(42)
n <- 2000
knapsack_objects <-
  data.frame(
    w=sample(1:4000, size = n, replace = TRUE),
    v=runif(n = n, 0, 10000)
  )

test_that('Brute force search',{
  expect_equal(brute_force_knapsack(knapsack_objects[1:8,],3500)$value, 16770)
  expect_equal(brute_force_knapsack(knapsack_objects[1:8,],3500)$elements, c(5,8))
  expect_equal(brute_force_knapsack(knapsack_objects[1:12,],3500)$value, 16770)
  expect_equal(brute_force_knapsack(knapsack_objects[1:12,],3500)$elements, c(5,8))
  expect_equal(brute_force_knapsack(knapsack_objects[1:8,],2000)$value, 15428)
  expect_equal(brute_force_knapsack(knapsack_objects[1:8,],2000)$elements, c(3,8))
  expect_equal(brute_force_knapsack(knapsack_objects[1:12,],2000)$value, 15428)
  expect_equal(brute_force_knapsack(knapsack_objects[1:12,],2000)$elements, c(3,8))
})


test_that('Brute force search',{
  expect_error(brute_force_knapsack(knapsack_objects,TRUE))
  expect_error(brute_force_knapsack(knapsack_objects,FALSE))
  expect_error(brute_force_knapsack(knapsack_objects,Inf))
  expect_error(brute_force_knapsack(knapsack_objects,-Inf))
})

test_that('Brute force search',{
  expect_error(brute_force_knapsack(c(1:00),10))
  expect_error(brute_force_knapsack(knapsack_objects,"x"))
  expect_error(brute_force_knapsack(c(1:00),10))
})

colnames(knapsack_objects) <- c("a","b")

test_that('Brute force search',{
  expect_error(brute_force_knapsack(knapsack_objects,2000))
})

colnames(knapsack_objects) <- c("w","v")
knapsack_objects$w <- -100

test_that('Brute force search',{
  expect_error(brute_force_knapsack(knapsack_objects,3500))
})
```

## Examples

```
brute_force_knapsack(x = knapsack_objects[1:12,], W = 3500)
brute_force_knapsack(x = knapsack_objects[1:8,], W = 2000)
brute_force_knapsack(x = knapsack_objects[1:12,], W = 2000)
brute_force_knapsack(x = knapsack_objects[1:12,], W = 2000)

greedy_knapsack(x = knapsack_objects[1:800,], W = 3500)
greedy_knapsack(x = knapsack_objects[1:1200,], W = 2000)

knapsack_dynamic(x = knapsack_objects[1:12,], W = 3500)
knapsack_dynamic(x = knapsack_objects[1:8,], W = 2000)
knapsack_dynamick(x = knapsack_objects[1:12,], W = 2000)
knapsack_dynamic(x = knapsack_objects[1:12,], W = 2000)

```


