---
title: "Vignette on package of Spotifyr"
author: "Yumeng Li, Mattias Karlsson, Ashraf Sarhan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Vignette Goal

The goal of this vignette is to introduce the package of Sportifyr and describe in detail about how the package of sportifyr connect to web API Spotify.

## Function Discription

In this package, we write the codes of three functions to access the data in API. The function are called getArtists(), auth(), getAudioFeatures() and getTracks(). 

By using auth()functions, the user is authenticated. It takes two parameters (client ID, secret) to check if it is right, and it returns 200 response with access token. Then the user can get access to the data of spotify artists, tracks and the features of audio.

A simple Shiny application is implemented in  the package to connect to the
API.


```
auth <- function(clientID, secret) {
  response = POST(
    'https://accounts.spotify.com/api/token',
    accept_json(),
    authenticate(clientID, secret),
    body = list(grant_type = 'client_credentials'),
    encode = 'form'
    #verbose(data_out = FALSE) Not necessary to print all information every time
  )
  stopifnot(response$status_code == 200)
  return(response)
}


getArtists <- function(artistIDs, access_token) {
  HeaderValue = paste0('Bearer ', access_token)
  URI = paste0('https://api.spotify.com/v1/artists?ids=', artistIDs)
  response = GET(url = URI, add_headers(Authorization = HeaderValue))
  return(response)
}


getTracks <- function(trackIDs, market, access_token) {
  HeaderValue = paste0('Bearer ', access_token)
  URI = paste0('https://api.spotify.com/v1/tracks?ids=', trackIDs, '&market=', market)
  response = GET(url = URI, add_headers(Authorization = HeaderValue))
  return(response)
}

getAudioFeatures <- function(trackIDs, access_token) {
  HeaderValue = paste0('Bearer ', access_token)
  URI = paste0('https://api.spotify.com/v1/audio-features?ids=', trackIDs)
  response = GET(url = URI, add_headers(Authorization = HeaderValue))
  return(response)
}


```

## Unit Tests

We implement function to connect to the API and download data to the R session. The unit test is written to test the inputs and outputs of the functions, the limits of the API configuration, whether the function always provide the given value for a specific set of inputs.


```

context('auth tests')

clientID = 'a223e7590d9043f1849bffa7ef86b102'
secret = 'aa351a255a8c49e7a4d69a8c2f893175'

test_that("Test Client Credentials Flow", {
  #Happy scenario
  expect_equivalent(auth(clientID, secret)$status_code, 200)
})

secret = 'aa351a255a8c49e7a4d69a8c2f893175###'

test_that("Test with invalid ID/secret", {
  #Sad scenario
  expect_error(auth(clientID, secret)$status_code != 200)
})


context('artists tests')

clientID = 'a223e7590d9043f1849bffa7ef86b102'
secret = 'aa351a255a8c49e7a4d69a8c2f893175'
artistID = '1HBjj22wzbscIZ9sEb5dyf'
token <- content(auth(clientID,secret))$access_token

test_that("Test valid ID/secret", {
  #Happy scenario
  expect_equivalent(getArtists(artistID,token)$status_code, 200)
})

artistID = 'aa351a255a8c49e7a4d69a8c2f893175###'

test_that("Test with invalid ID/secret", {
  #Sad scenario
  expect_error(getArtists(artistID,token)$status_code != 200)
})


context('tracks tests')

clientID = 'a223e7590d9043f1849bffa7ef86b102'
secret = 'aa351a255a8c49e7a4d69a8c2f893175'
artistID = '1HBjj22wzbscIZ9sEb5dyf'
trackIDs = '1CUVN2kn7mW5FjkqXTR2W1'
token <- content(auth(clientID,secret))$access_token

test_that("Test valid ID/secret", {
  #Happy scenario
  expect_equivalent(getTracks(artistID,"se",token)$status_code, 200)
})

artistID = 'aa351a255a8c49e7a4d69a8c2f893175###'

test_that("Test with invalid ID/secret", {
  #Sad scenario
  expect_error(getTracks(artistID,"se",token)$status_code != 200)
})

artistID = '1HBjj22wzbscIZ9sEb5dyf'

test_that("Test valid AudioFeatures", {
  #Happy scenario
  expect_equivalent(getAudioFeatures(artistID,"se",token)$status_code, 200)
})

artistID = 'aa351a255a8c49e7a4d69a8c2f893175###'

test_that("Test invalid ID, AudioFeatures", {
  #Sad scenario
  expect_error(getAudioFeatures(artistID,"se",token)$status_code != 200)
})

```


## Shiny application

The simple Shiny application that makes it possible to interactively analyze data using this API package. 

```

```


## More Examples


```
clientID = 'a223e7590d9043f1849bffa7ef86b102'
secret = 'aa351a255a8c49e7a4d69a8c2f893175'
artistID = '1HBjj22wzbscIZ9sEb5dyf'
trackIDs = '1CUVN2kn7mW5FjkqXTR2W1'
token <- content(auth(clientID,secret))$access_token

auth(clientID, secret)
getArtists(artistID,token)
getAudioFeatures(artistID,"se",token)
```

